### ISSUE TITLE
Bug dict default

### ISSUE THREAD

**Issue by Staruy** [HubSpot/jinjava#159]
CODE:
```
{% set a="1" %}
{% set b=b | default("2") %}
{% set c={"key": "value"} %}
{% set d=d | default({"key": "value"}) %}

Type: {{ type(a) }} - Value: {{ a }}
Type: {{ type(b) }} - Value: {{ b }}
Type: {{ type(c) }} - Value: {{ c }}
Type: {{ type(d) }} - Value: {{ d }}
Type: {{ type(c.key) }} - Value: {{ c.key }}
Type: {{ type(d.key) }} - Value: {{ d.key }}
```
OUTPUT:
```
Type: str - Value: 1
Type: str - Value: 2
Type: dict - Value: {key=value}
Type: str - Value: {key=value}
Type: str - Value: value
Type: null - Value: 
```
What the problem with the last output?

**Comment by boulter** [comment]
Hi @Staruy, 

the [`default` filter](https://github.com/HubSpot/jinjava/blob/master/src/main/java/com/hubspot/jinjava/lib/filter/DefaultFilter.java) currently only supports strings as values. Since `d` is a string, it has no `key` attribute.

If you're interested in adding this feature, I'm happy to review a pull request!

**Comment by gabru-md** [comment]
Hey @boulter , I would like to try my hands on this issue.
I'd really be happy to provide a PR for this, can you please brief me about the job to be done so that I can try it out? 😅
