### ISSUE TITLE
Fail on Unknown Incompatible with default filter

### ISSUE THREAD

**Issue by alexparlett** [HubSpot/jinjava#256]
Not sure what the desired behaviour should be here but feels wrong to me.

{{ foo | default('bar') }}

When Fail on unknown tokens is set to true and foo doesnt exist in the context this fails with a syntax exception instead of resolving the default filter.

**Comment by boulter** [comment]
Thanks for bringing it up. 

In my opinion this is doing exactly what is intended if you don't want to allow unknown tokens. default is intended more for if something wasn't set in the execution of the code, rather than something that should be coming from the context.

**Comment by alexparlett** [comment]
Not sure I agree with that thinking (and it definitely differs from how the implementation works in ansible). 

If you ever have a context that is built up dynamically, i.e from a selection of datasources. Then you'd have to preset all possible values to null that would want a default filter applied too (which you may not know)

**Comment by boulter** [comment]
I think you're right. The default filter in jinja2 works on undefined values based on http://jinja.pocoo.org/docs/2.10/api/#jinja2.StrictUndefined and http://jinja.pocoo.org/docs/2.10/templates/#list-of-builtin-filters

Instead of immediately throwing an exception, it uses a wrapper that throws an error for most uses.

This feature was originally contributed by @roopahc in https://github.com/HubSpot/jinjava/pull/98

**Comment by gabru-md** [comment]
@boulter I would like to work on this issue.
